"""users table

Revision ID: f5ff85c19241
Revises: 
Create Date: 2019-05-17 20:35:12.712228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ff85c19241'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('has_english', sa.Boolean(), nullable=True),
    sa.Column('has_latin', sa.Boolean(), nullable=True),
    sa.Column('has_math', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_has_english'), 'user', ['has_english'], unique=False)
    op.create_index(op.f('ix_user_has_latin'), 'user', ['has_latin'], unique=False)
    op.create_index(op.f('ix_user_has_math'), 'user', ['has_math'], unique=False)
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_has_math'), table_name='user')
    op.drop_index(op.f('ix_user_has_latin'), table_name='user')
    op.drop_index(op.f('ix_user_has_english'), table_name='user')
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
